[package]
name = "potool"
version = "0.1.0"
edition = "2021"
dependencies = "A simple tool used to generate po file from pot files and translation files."

[dependencies]
fltk = { version = "^1.4", features = ["fltk-bundled"] }